// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultGrammar() {
  return window['go']['main']['App']['GetDefaultGrammar']();
}

export function GetTokens(arg1) {
  return window['go']['main']['App']['GetTokens'](arg1);
}

export function ParseStepByStep(arg1, arg2) {
  return window['go']['main']['App']['ParseStepByStep'](arg1, arg2);
}

export function ParseString(arg1, arg2) {
  return window['go']['main']['App']['ParseString'](arg1, arg2);
}

export function ValidateGrammar(arg1) {
  return window['go']['main']['App']['ValidateGrammar'](arg1);
}
