// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function GetDefaultGrammar():Promise<string>;

export function GetTokens(arg1:string):Promise<Array<parser.Token>>;

export function ParseStepByStep(arg1:string,arg2:string):Promise<parser.ParseResult>;

export function ParseString(arg1:string,arg2:string):Promise<parser.ParseResult>;

export function ValidateGrammar(arg1:string):Promise<parser.ValidationResult>;
